name:
  1.$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- script: |
    npm install
  displayName: 'npm install dev dependencies'

- script: |
    cd $(Build.SourcesDirectory)\dist\resources\app
    npm install
  displayName: 'npm install dist dependencies'

- script: |
    gulp build --gulpfile build\gulpfile.js --buildVersion "$(Build.BuildNumber)" --buildBranch $(Build.SourceBranchName) --sourceFolder $(Build.SourcesDirectory) --outputFolder $(Build.SourcesDirectory)\dist
  displayName: 'run gulp'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Build.SourcesDirectory)\dotNet\Orb.sln'

- task: VSBuild@1
  displayName: 'Build .NET sln'
  inputs:
    solution: '$(Build.SourcesDirectory)\dotNet\Orb.sln'

    platform: 'Any CPU'

    configuration: Release

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)\dist
    #contents: '**'
    targetFolder: $(Build.SourcesDirectory)\dist_saw

- script: |
    npm test
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/Test-*.xml'
    searchFolder: '$(Build.SourcesDirectory)'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  enabled: false
  displayName: 'ESRP CodeSigning - Third Parties'
  inputs:
    FolderPath: $(Build.SourcesDirectory)
    ConnectedServiceName: 'Orb ESRP'

    Pattern: |
      /dist/**/*.dll

    UseMinimatch: true

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-231522",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-231522",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  enabled: false
  displayName: 'ESRP CodeSigning - Exe'
  inputs:
    FolderPath: $(Build.SourcesDirectory)
    ConnectedServiceName: 'Orb ESRP'

    Pattern: |
      /dist/**/*.exe
      /node_modules/electron-winstaller/**/update.exe
      /node_modules/electron-winstaller/**/squirrel.exe
      /node_modules/electron-winstaller/**/StubExecutable.exe

    UseMinimatch: true

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  enabled: false
  displayName: 'ESRP CodeSigning - SAW'
  inputs:
    FolderPath: $(Build.SourcesDirectory)
    ConnectedServiceName: 'Orb ESRP'

    Pattern: |
      /dist_saw/**/*.exe
      /dist_saw/**/*.dll

    UseMinimatch: true

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-236167",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-236167",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- script: |
    gulp createInstaller --gulpfile build\gulpfile.js --buildVersion "$(Build.BuildNumber)" --buildBranch $(Build.SourceBranchName) --sourceFolder $(Build.SourcesDirectory) --outputFolder $(Build.SourcesDirectory)\dist
  displayName: 'run gulp createInstaller'
  enabled: false

- script: |
    gulp createInstaller --gulpfile build\gulpfile.js --buildVersion "$(Build.BuildNumber)" --buildBranch $(Build.SourceBranchName) --sourceFolder $(Build.SourcesDirectory) --outputFolder $(Build.SourcesDirectory)\dist_saw
  displayName: 'run gulp createInstaller SAW'
  enabled: false

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  enabled: false
  displayName: 'ESRP CodeSigning - Installer'
  inputs:
    FolderPath: $(Build.SourcesDirectory)\installer
    ConnectedServiceName: 'Orb ESRP'

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning - Installer Saw'
  enabled: false
  inputs:
    FolderPath: $(Build.SourcesDirectory)\installer_saw
    ConnectedServiceName: 'Orb ESRP'

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-236167",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-236167",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- task: PublishBuildArtifacts@1
  enabled: false
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\dist'
    artifactName: 'Dist'

- task: PublishBuildArtifacts@1
  enabled: false
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\installer'
    artifactName: 'Installer'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\installer_saw'
    artifactName: 'Installer_saw'