name:
  1.$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install dev dependencies'

- script: |
    cd $(Build.SourcesDirectory)\dist\resources\app
    npm install
  displayName: 'npm install dist dependencies'

- script: |
    gulp build --gulpfile build\gulpfile.js --buildVersion "$(Build.BuildNumber)" --buildBranch $(Build.SourceBranchName) --sourceFolder $(Build.SourcesDirectory) --outputFolder $(Build.SourcesDirectory)
  displayName: 'run gulp'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  enabled: true
  displayName: 'ESRP CodeSigning - Third Parties'
  inputs:
    FolderPath: $(Build.SourcesDirectory)
    ConnectedServiceName: 'Orb ESRP'

    Pattern: |
      /dist/**/*.dll

    UseMinimatch: true

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-231522",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-231522",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  enabled: true
  displayName: 'ESRP CodeSigning - Exe'
  inputs:
    FolderPath: $(Build.SourcesDirectory)
    ConnectedServiceName: 'Orb ESRP'

    Pattern: |
      /dist/**/*.exe
      /node_modules/electron-winstaller/**/update.exe
      /node_modules/electron-winstaller/**/squirrel.exe
      /node_modules/electron-winstaller/**/StubExecutable.exe

    UseMinimatch: true

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- script: |
    gulp createInstaller --gulpfile build\gulpfile.js --buildVersion "$(Build.BuildNumber)" --buildBranch $(Build.SourceBranchName) --sourceFolder $(Build.SourcesDirectory) --outputFolder $(Build.SourcesDirectory)
  displayName: 'run gulp createInstaller'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning - Installer'
  inputs:
    FolderPath: $(Build.SourcesDirectory)\installer
    ConnectedServiceName: 'Orb ESRP'

    signConfigType: inlineSignParams

    OpusName: Orb

    OpusInfo: 'https://www.github.com/microsot/orb'

    inlineOperation: |
     [  {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolSign",
             "parameters": [
             {
                 "parameterName": "OpusName",
                 "parameterValue": "Microsoft"
             },
             {
                 "parameterName": "OpusInfo",
                 "parameterValue": "http://www.microsoft.com"
             },
             {
                 "parameterName": "Append",
                 "parameterValue": "/as"
             },
             {
                 "parameterName": "FileDigest",
                 "parameterValue": "/fd \"SHA256\""
             },
             {
                 "parameterName": "PageHash",
                 "parameterValue": "/NPH"
             },
             {
                 "parameterName": "TimeStamp",
                 "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
             }
             ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-230012",
             "operationSetCode": "SigntoolVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }]

- task: PublishBuildArtifacts@1
  enabled: true
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\node_modules\electron-winstaller\'

- task: PublishBuildArtifacts@1
  enabled: true
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\dist\orb_ExecutionStub.exe'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\installer'