name:
  2.0.$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    gulp default --gulpfile gulpfile.js
  displayName: 'npm install and run gulp'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'